# springboot 2.0 之前用server.context-path
#server.contextPath: /SerializedService
# springboot 2.0 之后 改为server.servlet.context-path
server:
  port: 9091
  servlet:
    context-path: /

spring.data.elasticsearch.repositories.enabled: true
spring.data.elasticsearch.cluster-nodes: 127.0.0.1:9300